### ISSUE TITLE
Sneak Peak 

### ISSUE THREAD

**Issue by zaidalyafeai** [zaidalyafeai/ARBML#1]
## Motivation 
As you know machine learning has proven its importance in many fields, like computer vision, NLP, reinforcement learning, adversarial learning, etc ..  Unfortunately, there is a little work to make machine learning accessible for Arabic-speaking people. 

## Goal
Our goal is to enrich the Arabic content by creating open-source projects and open the community eyes on the significance of machine learning. We want to create interactive **applications** that allow **novice** Arabs to learn more about machine learning and appreciate its advances. 

## Contributing  
Make sure you check the [issues](https://github.com/zaidalyafeai/ARBML/issues) to make sure we don't have repetitive simultaneous work. If your work has not been done [create an issue](https://help.github.com/en/articles/creating-an-issue) with a proper title. After finishing your work create a [pull requests](https://help.github.com/en/articles/about-pull-requests) to merge your contribution. Initially these are the projects we want to work on 

### Models
Create and train models using TensorFlow, Pytorch, etc ... 
- Letters and digits recognition (**done**)
- Diactrization (تشكيل) (**done**)
- Poem Generation (**done**)
- Translation (**In progress**) 
- Sentiment Analysis 
- Text Auto-Complete 
- Manuscript Reader  
- Part of speech classification (اسم , فعل ، حرف)
- Word Embedding (**done**) 

### Interfaces
Make the models accessible through 
- Web demos  (**In progress**)
- Colab and Jupyter notebooks  (**In progress**)
- Command line
- Desktop applications
- Gist codes 
- Articles en/ar related to Arabic.

### Datasets 
- Arabic Digits (**done**)
- Arabic Letters (**done**)

### Extra 
We can also contribute to other projects. For instance, help translate this [cheat sheet](https://github.com/shervinea/cheatsheet-translation/) to Arabic. 

## Community 
This is an open space community where we don't force members to do stuff. As long as you are motivated and have the passion to help the community to grow you are always welcomed. More importantly, _plan your ideas well and take the time before committing yourself into a project_. 

## Resources 
As a start we will start on Github for hosting the website, models, datasets and other contents. Unfortunately, there is a limitation on the space that will hunt us in the future. _Please let us know what you suggest on that matter_. 

## Code of Ethics 
We are an open community. So, if you reuse a model/code/tutorial please make sure to mention the original authors and check the copyright notice. 

## Sponsors 
We are not sponsored and all the members are voluntarily working on the projects. 

## License 
This project will be under the [MIT](https://opensource.org/licenses/MIT) license.

**Comment by MagedSaeed** [comment]
This is a marvelous start @zaidalyafeai . shall the project scope include tutorials written in either way, Arabic or English? This will be a awesome addition. 
Thanks for this initiative.

**Comment by farisology** [comment]
I appreciate the initiative thank you for taking the effort @zaidalyafeai .

**Comment by MarchWorks** [comment]
I can make the website, if you have a model that I can follow it will be better.
For Resources we can make use torrent and put the magnet links in the website.

**Comment by MagedSaeed** [comment]
Hey @MarchWorks
We currently had a good progress in this regard. However, we definitely need a team to maintain and enhance.
Appreciate your interest. 
:)

**Comment by zaidalyafeai** [comment]
@MarchWorks thanks for your suggestions. Really appreciate that :).  torrents are blocked in my institution so we don't prefer that. We might consider paid services like amazon (depending on the price) but we are still in the beginning stages.

**Comment by zaidalyafeai** [comment]
@all-contributors please add @MagedSaeed  for design, ideas and platform.

**Comment by zaidalyafeai** [comment]
@all-contributors please add @MarchWorks for ideas.
