### ISSUE TITLE
AraBert

### ISSUE THREAD

**Issue by zaidalyafeai** [zaidalyafeai/ARBML#18]
Hey All, 

This is a temporary issue to discuss the idea of training a Bert model specific for Arabic - **AraBert**. We will move to another repository once we have a clear understanding of the problem and how to tackle it as well as having experts in the field. There are three main issues to discuss here and I want your opinions about them 

1. Dataset:  we can use the avilable Wiki [dumbs](https://dumps.wikimedia.org/). If you have more suggestions let us know. 
2. Models: We can use the available Bert [models](https://github.com/google-research/bert). 
3. Training: We need sponsor for that to train in the cloud. If you can help with that issue please let us know. 

If you have any comments on any of the above points don't hesistate to respond. More importantly, if you have any experience in training large models let us know that.  Open source contribution is a slow and lengthy process and it might take us a some time to finish the project. If you are planning to contribute please be sure to cut some time for this project. 

Thanks
Zaid

**Comment by itinawi** [comment]
How is this different from the [Multilingual BERT](https://github.com/google-research/bert/blob/master/multilingual.md#data-source-and-sampling) which was trained using the wikidata dumps of 100+ languages?

It's a great project nonetheless, and I'd be happy to contribute. We would benefit a lot more if we train on a bigger Arabic corpus than just the Wikidata.

Compute remains an issue so we would need to find sponsors for cloud training.

**Comment by zaidalyafeai** [comment]
@itinawi That is a great point. As you said multilingual bert was trained on many languages which makes it weaker in language-sepcific tasks. Furthermore, many other language-sepcific models has shown to outperform Multilingual bert in many tasks. For instance, Spanish Bert outperforms multilingual bert as shown in this [repository](https://github.com/dccuchile/beto). There are other benchmarsk on French for instance as shown using [CamemBert](https://arxiv.org/pdf/1911.03894.pdf). Moreover, multilingual bert doesn't preform well on low-resource languages.  Not to mention the vocabulary constraints on mBert.

**Comment by k-halid** [comment]
Hello @zaidalyafeai, 

AraBert is a good idea for a more robust Arabic language model. In addition, traditional Bert uses many aspects such as Bert tokenizer that did not account for Arabic. Therefore, it is necessary to have AraBert which will not contribute only to Arabic natural language processing, but it may highlit some important points related to natural language processing and more unified models in the future. 

For me, I have trained the vanilla transformer before as a language model. Therefore, I would be happy to contribute.

**Comment by mobarmg** [comment]
Hi Zaid,
I am interested in your project and we in Naseej AI Lab could sponsor it. What would be the estimated computing resources needed for the project?

**Comment by abdallah197** [comment]
Hi @zaidalyafeai 
I more than interested. I have been working with bert for a while. Would it be possible to make a slack channel?

**Comment by EsamGhaleb** [comment]
Cool idea. 

I could contribute to coding and developing, but I don't have specific experience in NLP.

BTW, Al-Bert would be a nice name as well :)

**Comment by azamalfayez** [comment]
I am interested.count me in..

**Comment by Fatima-200159617** [comment]
Salam alaykoum Zaid,
I am sending this message on behalf of the bigIR group the "Information Retrieval and Big Data" research group at Qatar University. 
Thanks for this initiative, we are interested in contributing to this project. Please let us know how can we help.
Our group published the ArabWeb16 dataset with 150M Arabic Web pages with significant coverage of dialectal Arabic as well as Modern Standard Arabic. 
The dataset can be a great candidate for training the BERT model. Please find below the link to the dataset paper. 
https://dl.acm.org/doi/abs/10.1145/2911451.2914677

**Comment by HashimHL** [comment]
Regarding the dataset.

I thought about social media sites like twitter, facebook, askfm etc but their data isn't clean and long enough, it requires a lot of preprocessing, even then it's hard to get the data by obeying their policies.

There is a similar site to Wikipedia called mawdoo3.com the articles are clean and don't carry misspellings,Also it's written in classical Arabic. The data on the website can be used under the rules of ”[Fair use](https://mawdoo3.com/%D8%A7%D8%AA%D9%81%D8%A7%D9%82%D9%8A%D8%A9_%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85) ” like for educational purposes. Based on the website claim there are more than 150k articles, just for comparison, Wikipedia has 118k Arabic ones, however, article’s length may vary so that might not be a good comparison.

I also had a thought about free Arabic ebooks but what I have found most of them are old and contain a hard Arabic language on top of that they aren't PDF just scanned images so pulling the text out of those will not gonna be an easy task and I'm not sure about the ethics here since there might be some copyright rules.

If I had the opportunity to help I would happily do so.

**Comment by KhaledEssam** [comment]
I think using some data from OPUS (http://opus.nlpl.eu/) which contains subtitles, news, and other resources might help the model generalize outside of Wikipedia-like use cases maybe?

**Comment by mani144** [comment]
Wh can use books that is written in Arabic with PDF format, but I'm not sure if these books is scanned as pictures or written as a text

**Comment by MagedSaeed** [comment]
@mani144  You proposed a very nice idea. Is anyone here familiar with a good Arabic OCR? These scanned books are not handwrittin. This might make it easier to extract text. What do you thin?

**Comment by mobarmg** [comment]
For Arabic Corpora we could provide you with our naseej.net news database [1998-2012] more than 240K page.

**Comment by moaaztaha** [comment]
We can use videos with Arabic captions on youtube like videos from [BBC Arabic](https://www.youtube.com/results?search_query=bbc+arabic&sp=EgIoAQ%253D%253D)

**Comment by zaidalyafeai** [comment]
@abdallah197 yes, at this moment we need a slack channel. Would you like to create one for this purpose ?

**Comment by abedkhooli** [comment]
It seems that **compute** is the easiest part as some have already proposed to sponsor it (either GPU or TPU).
**Models**: can use transformers based on En BERT (or train from scratch) - maybe test both.
**Corpus**: I suggest we curate a large enough one with good coverage of topics and style - may be a mixture of Arabic Wikipedia, Mawdoo3's content (if they are willing to share it), QU, Naseej and some books (need to do some processing including de-duplication of same/similar articles). 
I trained a **MultiFiT** model a few days ago (based on Ar wiki) and it performed well in classification tasks (https://www.linkedin.com/feed/update/urn:li:activity:6627500876145672192/). I agree multilingual BERT is almost useless for Arabic (very limited vocabulary representation).

**Comment by NightXBurn** [comment]
Hi everyone, very happy to see _AraBert_ project thank you @zaidalyafeai. I want to contribute with some ideas that can make _AraBert_ performant. 

- Knowing that in Arabic **diacritics** have an impact on the _semantic_ of words we would train _AraBert_ with _diacritics_ not only **nondiactritized** words. Thus, for _tokenization_, we can use the new **Dropout BPE** method available in _YouTokenToMe_ library which can handle _diacritics_ token and also better than vanilla **Bert tokenizer**. 

- For dataset, in addition to the corpora proposed previously, we can add the _books_ proposed in [tashkeela](https://www.kaggle.com/linuxscout/tashkeela) which contains **old writing styles** and **diacritized words**

- **Multilingual BERT** gives an amazing representation of Arabic words thanks to Google team, it can be used to solve state of the art problems in Arabic language. It uses _WordPiece_ tokenizer which can handle _rich vocabulary_ languages such as Arabic. In the task [link](https://www.kaggle.com/c/nsurl-2019-task8) the models that apply multilingual BERT are the best. However, it cannot handle diacritics which is a phenomenon that occurs in Arabic language.

**Comment by k-halid** [comment]
Hello everyone, 

I have some ideas related to the points mentioned in @zaidalyafeai post. First of all, I think we can use the dataset from El-khair et al corpus which is to my knowledge one of the largest Arabic corpus. Also, we can use the Wiki Arabic corpus. 

For the model, I suggest that we use both TensorFlow and Pytorch Bert model if it is possible. First, I am more expert in Pytorch. Second, this will open more opportunities for ML developers who interested in Arabic NLP to expand this work in some specific NLP tasks.

**Comment by amaloraini** [comment]
Salam, 

Thanks @zaidalyafeai  for the brilliant idea. 

I'm currently waiting for BERT-base to finish training on Arabic Wikipedia articles. I'm using TF and it has been more than one week, but it should finish soon. I will see if it outperforms the original multilingual BERT and I will share all my findings.

We have 3 Geforce GTX 1080 Ti and they work fine if you limit the batch size to 8 (yet, take too long to finish). 

I have done the following preprocessing steps: 
1- Removed all diacritics 
2- Normalized "alif" 
3- Used BPE dropout to create the vocab and to tokenize the words

If someone has access to more resources, it might be a good idea to try out RoBERTa.

I will be happy to contribute, so please let me know if you need any additional information.

Abdulrahman

**Comment by OS47** [comment]
Hi zaid, i have a desire to contribute with the community. Still not reaching to BERT concepts but having good background in DL & NLP. 

Hoping the community growing and serve arabic contents

**Comment by fadybaly** [comment]
Hello everyone,

My friend @WissamAntoun and I have just finished training AraBERT. we trained it on a 21GB with 3.7B tokens arabic corpus.

as for the preprocessing steps we decided to go with two approaches, and both will be uploaded to huggingface very shortly.

for the first approach we:
1- removed diacritics
2- replaced the urls, emails, numbers, mentions with unique tokens
3- used Farasa tokenizer to separate ahrof el wasel و, ل, ب, ف, ال and trained a sentencepiece vocab with vocab size of 64k.

for the second approach we didn't replace the numbers with unique tokens and we used the Farasa tokenizer more heavily as to remove the suffixes and prefixes.

regarding downstream tasks we evaluated on several sentiment analysis dataset as well as NER and QA, the models outperformed SOTA in all the tasks.
the results will be published soon after we submit a paper detailing our approaches to OSACT4.

we are also planning to make it compatible with the transformers library (adapting the tokenizer)

**Comment by itinawi** [comment]
That's awesome news Fady! Moving the needle forward in a field that needs much love. Are you guys planning on releasing the pre-trained model? I'm sure a lot of researchers here would love to play around with that.

**Comment by abedkhooli** [comment]
This is really great @fadybaly and @WissamAntoun - looking forward to check the models @HF. Can you describe the corpus content used in the training?

**Comment by fadybaly** [comment]
> That's awesome news Fady! Moving the needle forward in a field that needs much love. Are you guys planning on releasing the pre-trained model? I'm sure a lot of researchers here would love to play around with that.

of course, we're releasing a tensorflow version to huggingface tomorrow, with pytorch following it shortly afterwards

**Comment by fadybaly** [comment]
> This is really great @fadybaly and @WissamAntoun - looking forward to check the models @hf. Can you describe the corpus content used in the training?

it's trained on modern standard arabic data collected from open source datasets and heavily cleaned web scraped news articles websites.

**Comment by mobarmg** [comment]
Great efforts @fadybaly , can not wait to test  your model.

**Comment by ajamjoom** [comment]
`of course, we're releasing a tensorflow version to huggingface tomorrow, with pytorch following it shortly afterwards`

Amazing! would be great if you can share a link here once it's ready. Thanks

Looking forward to trying it out.

**Comment by zaidalyafeai** [comment]
@fadybaly thanks for efforts. We will try to follow your steps to train a larger model. Btw, are you affiliated with hugging face ? Why did you decide to publish the models there first?  I mean you can create your own repo with enough information and explanation then upload the models there if you are interested!

**Comment by abedkhooli** [comment]
> it's trained on modern standard arabic data collected from open source datasets and heavily cleaned web scraped news articles websites.
Can you please share random samples of the preprocessed corpus (just before tokenization) - say around 10 MB of randomly selected texts limited to one page per text item (1st approach).

**Comment by abedkhooli** [comment]
This French BERT model may be helpful in the coding work: https://github.com/getalp/Flaubert 
(in addition to  @fadybaly and @WissamAntoun  work if code is released, of course). 
If a larger corpus is to be used, I suggest it is shared on a central server with enough space so different pre-processing/selection options can be used. Compute sponsors can link nodes as well (some control on resource usage needed - ex. approve models to train for x days).

**Comment by WissamAntoun** [comment]
Hi everyone,

@fadybaly and i managed to put together a small demo on fine-tuning our araBERT.
(Colab: https://colab.research.google.com/drive/1KSy89fAkWt6EGfnFQElDjXrBror9lIZh,
araBERT TF ckpt: https://drive.google.com/open?id=1GQr8ue04rsvkOO3GieYTWnCOmB3-CNJz)

To use araBERT you will need access to the Farasa Segmenter since in this version of araBERT we segmented the words before we did sentencepiece tokenization. (we are currently training another version of araBERT that won't use segmented words, but we think that the performance might suffer a bit because the effective vocabulary will be heavily reduced, we think it will be done by next week).

@zaidalyafeai, no we aren't affiliated with huggingface, but we think releasing a compatible version is really helpful for the community. We also have a fork of the bert repo with the tokenizer made compatible with our vocab, we still need to figure out the best way to make hugginface's BertTokenizer compatible.

We also have the ability to train a Bert-large model, but we prioritized the base model because while Bert-Large will perform better, it is still impractical to use for most applications due to the compute requirement.

We are also finishing the write up for an arxiv preprint detailing the pretraining processes and data

**Comment by zaidalyafeai** [comment]
@WissamAntoun very happy to see some nlp work on Arabic. I hope that gets the recognition it deserves (will help on that of course) . I encourage you to spend some time to update the fork readme so future researchers can benefit from your work.

**Comment by abedkhooli** [comment]
> Our group published the ArabWeb16 dataset with 150M Arabic Web pages with significant coverage of dialectal Arabic as well as Modern Standard Arabic.
> The dataset can be a great candidate for training the BERT model. Please find below the link to the dataset paper.
> https://dl.acm.org/doi/abs/10.1145/2911451.2914677    

@Fatima-200159617  Is http://bigir1.qu.edu.qa:3000/ down? Is there an open format (txt, csv) version of the labeled datasets?

**Comment by Fatima-200159617** [comment]
> 
> 
> > Our group published the ArabWeb16 dataset with 150M Arabic Web pages with significant coverage of dialectal Arabic as well as Modern Standard Arabic.
> > The dataset can be a great candidate for training the BERT model. Please find below the link to the dataset paper.
> > https://dl.acm.org/doi/abs/10.1145/2911451.2914677
> 
> @Fatima-200159617 Is http://bigir1.qu.edu.qa:3000/ down? Is there an open format (txt, csv) version of the labeled datasets?

The dataset is available and can be accessed from the link below
https://sites.google.com/view/arabicweb16/home
You can search the entire ArabicWeb16 dataset from the website. Downloading the dataset requires signing the agreement first, then you can download it as WARC files.
Which labeled dataset you are planning to use the Content-based Categorized Dataset or the Dialect-labelled Dataset?
The server is under maintenance now, I will inform you when it is up soon.

**Comment by zaidalyafeai** [comment]
Hey All, 

Thanks for your informative feedback and resources you shared in this thread. I didn't expect to have this thoughtful and brilliant community who care about Arabic research. That being said, as shown in this thread there seems to be some efforts to publish Bert in Arabic and we don't want to do a repatitve work. Our plans will change slightly to build on that work and hopefully extend the community to work on other models. Please keep in mind that our main objective is to enrich the Arabic research regardless of lack of support and resources. Personally, I am not looking for paybacks besides learning from this awesome community. In short, if you would like to continue this journey to learn, challenge and hopefully produce something fruitful, thumbs up and I will create a new repository to discuss our next steps. 

~Zaid

**Comment by Jeddadh** [comment]
Hello,

This is a great idea ! I am very interested in the project. I have a good experience with BERT (Training and finetuning NLP models in general) and a good understanding of the Arabic language (grammar, vocabulary ... ).
I will be glad to contribute to the project.

**Comment by abedkhooli** [comment]
> Which labeled dataset you are planning to use the Content-based Categorized Dataset or the Dialect-labelled Dataset?

Actually, I found https://sites.google.com/view/arabicweb16/home was looking for the dataset and tried to see a sample of text contents to access suitability for an Arabic BERT model. Will wait till server is up (no access to resources that can deal with the full dataset).

**Comment by abedkhooli** [comment]
> Our plans will change slightly to build on that work and hopefully extend the community to work on other models.

I think there is room for various efforts in this field. Some have already taken place and these need not be repeated (but great to learn from). Collective efforts are best but may take time for larger teams (less agility), so smaller teams may be a good option (provided infrastructure is available).

**Comment by zaidalyafeai** [comment]
It seems some people are interested in creating the repository. I was hoping for a larger number but maybe we can convince others later. Now, I need your suggestions for a cool name for the repository. Our next step is a collecting a very large dataset. hopeuflly something like +100 GB.

**Comment by Mohammed-Salti** [comment]
I think the e-books available on [Hindawi](https://www.hindawi.org/books/) can be a great resource because most of them are available in the _epub_ format or even as raw text. Currently there are around 1800 books on a variety of topics and most of them are in Modern Standard Arabic.
I'm not sure, but I think there aren't any legal issues regarding using their data because they say [here](https://www.hindawi.org/about/) that they are a nonprofit organization.

**Comment by MagedSaeed** [comment]
@Mohammed-Salti Thanks for your useful suggestion. I started downloading them. The script may finish by tonight if I did not face any issues. I will share the code later on a separate repository.

**Comment by Fatima-200159617** [comment]
> 
> 
> Hello everyone,
> 
> My friend @WissamAntoun and I have just finished training AraBERT. we trained it on a 21GB with 3.7B tokens arabic corpus.
> 
> as for the preprocessing steps we decided to go with two approaches, and both will be uploaded to huggingface very shortly.
> 
> for the first approach we:
> 1- removed diacritics
> 2- replaced the urls, emails, numbers, mentions with unique tokens
> 3- used Farasa tokenizer to separate ahrof el wasel و, ل, ب, ف, ال and trained a sentencepiece vocab with vocab size of 64k.
> 
> for the second approach we didn't replace the numbers with unique tokens and we used the Farasa tokenizer more heavily as to remove the suffixes and prefixes.
> 
> regarding downstream tasks we evaluated on several sentiment analysis dataset as well as NER and QA, the models outperformed SOTA in all the tasks.
> the results will be published soon after we submit a paper detailing our approaches to OSACT4.
> 
> we are also planning to make it compatible with the transformers library (adapting the tokenizer)

Salam,
Thanks for the initiative and for sharing your approach, could you please inform about the  computational resources that you needed to train the model, GPUs, TPUs and how long did it take to be trained?

**Comment by abedkhooli** [comment]
> I think there is room for various efforts in this field. Some have already taken place and these need not be repeated (but great to learn from). Collective efforts are best but may take time for larger teams (less agility), so smaller teams may be a good option (provided infrastructure is available). 

The dataset I published on Kaggle (https://www.kaggle.com/abedkhooli/arabic-bert-corpus) went through several cleaning iterations and can be used as a base model to build on. I also have the HDF5 files (14GB - can't upload to Kaggle from G drive) and can provide the links (2 zipped files, phase 1 and phase 2) if anyone has access to appropriate compute (I don't). Expected to train in less than one day on 8 core Nvidia gpu.

**Comment by zaidalyafeai** [comment]
Thanks @abedkhooli, this is a very nice resource.

**Comment by mapmeld** [comment]
This HuggingFace article about using their tokenizers and transformers packages comes at a great time: https://huggingface.co/blog/how-to-train

Among other things, I didn't know about OSCAR's deduped CommonCrawl datasets, which includes 32GB of Arabic text

**Comment by zaidalyafeai** [comment]
Hey All, I created the repository https://github.com/zaidalyafeai/Arabert. We are going to use the Oscar's deduplicated dataset shared by @mapmeld. In terms of computation, I have a subscription on google cloud to use TPUs for one month.

**Comment by zaidalyafeai** [comment]
Hey All, I created a slack channel to chat more about the project. If you are still intereseted/serious about the project send me an email to alyafey22(at)gmail(dot)com.

**Comment by Jason3900** [comment]
> Salam alaykoum Zaid, I am sending this message on behalf of the bigIR group the "Information Retrieval and Big Data" research group at Qatar University. Thanks for this initiative, we are interested in contributing to this project. Please let us know how can we help. Our group published the ArabWeb16 dataset with 150M Arabic Web pages with significant coverage of dialectal Arabic as well as Modern Standard Arabic. The dataset can be a great candidate for training the BERT model. Please find below the link to the dataset paper. https://dl.acm.org/doi/abs/10.1145/2911451.2914677

Hey, I found your work very interesting and I'm doing some NLP research on Arabic. However, I encountered a problem after filling out the form. There's no username or password I received to download the data. Thus, I'm wondering if it's possible that you send me the username and password for downloading. By the way, if you have cleaned text data extracted from it, it's even better.
