### ISSUE TITLE
Add 'Arabic Font Classification'

### ISSUE THREAD

**Issue by mhmoodlan** [zaidalyafeai/ARBML#20]
_Even though it is not explicitly mentioned, but it looks like this repo is NLP focused, so let me know if this is out of context._
I'd like to add [Arabic Font Classification](https://mhmoodlan.github.io/blog/arabic-font-classification) to the list of projects. This project is about tackling the visual font recognition problem for Arabic fonts by synthesizing data and addressing domain mismatch challenges. It features a post discussing the main ideas with a demo and an [open-sourced codebase](https://github.com/mhmoodlan/arabic-font-classification/) and [dataset](https://github.com/mhmoodlan/arabic-font-classification/releases/tag/v0.1.0).

**Comment by zaidalyafeai** [comment]
@mhmoodlan it is nlp focused but we have other subjects that are related to Arabic like speech recognition, digits classification, object detection and image captioning. So, anything that is related to Arabic is always welcomed.

**Comment by mhmoodlan** [comment]
a PR #21 adding this project is open now

**Comment by zaidalyafeai** [comment]
@all-contributors please add @mhmoodlan for ideas and code.
